name: Release

on:
  push:
    branches: ["main"]
    tags:
      - "*"

jobs:
  release:
    permissions:
      # grant the github token the ability to modify release tags
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # fetch all history for goreleaser to work correctly
        # https://goreleaser.com/ci/actions/#workflow
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Run Go Release
      run: |
        mkdir spin-plugin-buildx-canary-darwin-arm64
        GOOS=darwin GOARCH=arm64 go build -o spin-plugin-buildx-canary-darwin-arm64/buildx main.go
        cd spin-plugin-buildx-canary-darwin-arm64 && tar -czvf ../spin-plugin-buildx-canary-darwin-arm64.tar.gz buildx && cd -

        mkdir spin-plugin-buildx-canary-darwin-amd64
        GOOS=darwin GOARCH=amd64 go build -o spin-plugin-buildx-canary-darwin-amd64/buildx main.go
        cd spin-plugin-buildx-canary-darwin-amd64 && tar -czvf ../spin-plugin-buildx-canary-darwin-amd64.tar.gz buildx  && cd -

        mkdir spin-plugin-buildx-canary-linux-arm64
        GOOS=linux GOARCH=arm64 go build -o spin-plugin-buildx-canary-linux-arm64/buildx main.go
        cd spin-plugin-buildx-canary-linux-arm64 && tar -czvf ../spin-plugin-buildx-canary-linux-arm64.tar.gz buildx && cd -

        mkdir spin-plugin-buildx-canary-linux-amd64
        GOOS=linux GOARCH=amd64 go build -o spin-plugin-buildx-canary-linux-amd64/buildx main.go
        cd spin-plugin-buildx-canary-linux-amd64 && tar -czvf ../spin-plugin-buildx-canary-linux-amd64.tar.gz buildx && cd -
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload assets
      run: |
        gh release upload canary *.tar.gz --clobber
        gh release delete-asset canary buildx.json -y || true
        gh release delete-asset canary checksums-canary.txt -y || true
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Release Plugin
      uses: rajatjindal/spin-plugin-releaser@v1
      with:
        github_token: ${{ github.token }}
        upload_checksums: true
        template_file: contrib/spin-plugin.json.tmpl
